import { ScanData, VulnerabilityFinding } from '../types';

export function generateMarkdownReport(scan: ScanData, aiAssessment?: string): string {
  const { stats, hosts, vulnerabilities } = scan;

  const criticals = vulnerabilities.filter((v) => v.severity === 'critical');
  const highs = vulnerabilities.filter((v) => v.severity === 'high');
  const mediums = vulnerabilities.filter((v) => v.severity === 'medium');
  const lows = vulnerabilities.filter((v) => v.severity === 'low');

  let md = `# NETWORK SECURITY ASSESSMENT & VULNERABILITY AUDIT REPORT
**Generated by Nmap Sentinel Security Suite**  
**Audit Timestamp:** ${scan.scanTime}  
**Format Analyzed:** ${scan.inputFormat.toUpperCase()}  
**Target Hosts Scanned:** ${stats.totalHosts} (${stats.hostsUp} active)  
**Total Open Ports Identified:** ${stats.totalOpenPorts}  
**Overall Security Posture Score:** ${stats.overallScore}/100 (${stats.attackSurfaceRating} Attack Surface)

---

## 1. EXECUTIVE SUMMARY

An automated vulnerability audit and perimeter analysis was performed across **${stats.totalHosts} network endpoints**. 

The assessment identified **${vulnerabilities.length} total potential weak spots**:
- **Critical Severity (CVSS 9.0 - 10.0):** ${criticals.length} finding(s)
- **High Severity (CVSS 7.0 - 8.9):** ${highs.length} finding(s)
- **Medium Severity (CVSS 4.0 - 6.9):** ${mediums.length} finding(s)
- **Low Severity (CVSS 0.1 - 3.9):** ${lows.length} finding(s)

${
  criticals.length > 0
    ? `> **URGENT SECURITY NOTICE:** Immediate adversary exploitation risk detected! Identified ${criticals.length} critical vulnerabilities capable of remote unauthenticated code execution or complete system takeover.`
    : `> Perimeter posture is relatively stable, though ${highs.length} high-severity configurations require timely hardening.`
}

${
  aiAssessment
    ? `\n### AI Executive Threat Intelligence Briefing\n${aiAssessment}\n`
    : ''
}

---

## 2. KEY VULNERABILITY FINDINGS

| Severity | Host | Port / Proto | Vulnerability Title | CVSS | CVE Reference | Status |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
${vulnerabilities
  .map(
    (v) =>
      `| **${v.severity.toUpperCase()}** | \`${v.hostIp}\` | \`${v.port}/${v.protocol}\` | ${v.title} | **${v.cvss}** | ${v.cveId || 'N/A'} | ${v.status.toUpperCase()} |`
  )
  .join('\n')}

---

## 3. DETAILED WEAK SPOT BREAKDOWN & ACTIONABLE REMEDIATION

${vulnerabilities
  .map((v, idx) => {
    const cmds = v.remediation.commands
      ?.map((c) => `\`\`\`bash\n# ${c.label} (${c.os || 'generic'})\n${c.command}\n\`\`\``)
      .join('\n\n');

    return `### 3.${idx + 1}. [${v.severity.toUpperCase()}] ${v.title}
- **Target Endpoint:** \`${v.hostIp}\` ${v.hostName ? `(${v.hostName})` : ''} - Port \`${v.port}/${v.protocol}\` (${v.service})
- **CVSS Base Score:** **${v.cvss}** | **Category:** ${v.category}
${v.cveId ? `- **CVE Identifier:** [${v.cveId}](https://nvd.nist.gov/vuln/detail/${v.cveId})` : ''}
${v.cweId ? `- **CWE Classification:** ${v.cweId}` : ''}

#### Vulnerability Description
${v.description}

#### Threat Impact
${v.impact}

#### Remediation Instructions
**${v.remediation.title}**
${v.remediation.steps.map((s, i) => `${i + 1}. ${s}`).join('\n')}

${cmds ? `#### Recommended Hardening Commands:\n${cmds}` : ''}
`;
  })
  .join('\n---\n\n')}

---

## 4. ASSET INVENTORY & EXPOSED SERVICES

${hosts
  .map(
    (h) => `### Host: \`${h.ip}\` ${h.hostname ? `(${h.hostname})` : ''}
- **Status:** ${h.status.toUpperCase()} (Latency: ${h.latencyMs} ms)
- **Operating System:** ${h.osName || 'Unidentified OS'} ${h.osAccuracy ? `(${h.osAccuracy}% accuracy)` : ''}
- **Hardware / MAC:** \`${h.macAddress || 'N/A'}\` ${h.vendor ? `(${h.vendor})` : ''}
- **Calculated Host Risk Score:** ${h.riskScore}/100

| Port | Protocol | State | Service | Version / Banner |
| :--- | :--- | :--- | :--- | :--- |
${h.ports
  .map(
    (p) =>
      `| \`${p.portNumber}\` | \`${p.protocol}\` | \`${p.state}\` | \`${p.service}\` | ${p.version || p.product || '-'} |`
  )
  .join('\n')}
`
  )
  .join('\n')}

---

## 5. STRATEGIC REMEDIATION ROADMAP

### Phase 1: Immediate Containment (0 - 24 Hours)
1. Close or firewall perimeter access to exposed databases (Redis 6379, MySQL 3306, PostgreSQL 5432, Elasticsearch 9200).
2. Decommission or block legacy unencrypted management daemons (Telnet 23, VNC 5900, cleartext FTP 21).
3. Disable SMBv1 across all Windows machines to mitigate EternalBlue lateral propagation.

### Phase 2: Short-Term Remediation (1 - 7 Days)
1. Patch vulnerable web services (upgrade Apache HTTP Server >= 2.4.51).
2. Enforce SSH key-based authentication and disable root login on all Linux servers.
3. Place internal administration endpoints (Kubernetes API 6443, Docker socket, RDP 3389) behind zero-trust VPN or bastion jumps.

### Phase 3: Continuous Monitoring & Architecture (Ongoing)
1. Establish automated weekly differential Nmap scans.
2. Implement centralized SIEM and network intrusion detection (Snort / Suricata / Zeek).
3. Conduct credential audits to ensure no default passwords remain active.

---
*Report generated automatically by Nmap Sentinel. Confidential security document.*
`;

  return md;
}

export function generateCsvExport(vulnerabilities: VulnerabilityFinding[]): string {
  const headers = ['ID', 'Host_IP', 'Hostname', 'Port', 'Protocol', 'Service', 'Title', 'Severity', 'CVSS', 'CVE_ID', 'Category', 'Status', 'Remediation_Title'];
  const rows = vulnerabilities.map((v) => [
    `"${v.id}"`,
    `"${v.hostIp}"`,
    `"${v.hostName || ''}"`,
    v.port,
    `"${v.protocol}"`,
    `"${v.service}"`,
    `"${v.title.replace(/"/g, '""')}"`,
    `"${v.severity}"`,
    v.cvss,
    `"${v.cveId || ''}"`,
    `"${v.category}"`,
    `"${v.status}"`,
    `"${v.remediation.title.replace(/"/g, '""')}"`,
  ]);

  return [headers.join(','), ...rows.map((r) => r.join(','))].join('\n');
}

export function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
